version: '3.8'

services:
  docker-gs-ping-roach:
    depends_on: 
      - bookstore
    build:
      context: .
    container_name: golangwebapi
    hostname: golangwebapi
    networks:
      - mynet
    ports:
      - 8080:8080
    environment:
      - MYSQL_USER=${MYSQL_USER:-totoro}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:?}
      - MYSQL_HOST=${MYSQL_HOST:-db}
      - MYSQL_PORT=${MYSQL_PORT:-26257}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-mydb}
    deploy:
      restart_policy:
        condition: on-failure
  bookstore:
    image: mysql
    container_name: bookstore
    hostname: db
    networks:
      - mynet
    ports:
      - 26257:26257
      - 8080:8080
    volumes:
      - bookstore
    command: start-single-node --insecure

volumes:
  bookstore:

networks:
  mynet:
    driver: bridge

